"""add comment

Revision ID: 2feb210066a7
Revises: 54cfdbcd8ec9
Create Date: 2014-04-16 22:25:17.038861

"""

# revision identifiers, used by Alembic.
revision = '2feb210066a7'
down_revision = '54cfdbcd8ec9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('content', sa.String(length=160), nullable=False),
    sa.Column('up', sa.Integer(), nullable=False),
    sa.Column('down', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    ### end Alembic commands ###
